# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    working_directory: /app
    docker:
       - image: docker:18.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install CircleCI dependencies
          command: |
            apk add --no-cache curl curl-dev py-pip
            pip install --upgrade pip
            pip install docker-compose
      - run:
          name: Move repo into subfolder
          command: |
            cp -r /app/. ~/tw-server
            mv -v ~/tw-server /app/tw-server
      - run:
          name: Clone tw-base
          command: git clone --branch develop --depth 1 git@github.com:adriancarriger/tw-base.git
      - run:
          name: Get tw-* dependencies
          command: ./tw-base/init.sh
      - run:
          name: Build Docker images
          command: docker-compose -f ./tw-base/docker-compose.yml build
      - run:
           name: Start Docker
           command: docker-compose -f ./tw-base/docker-compose.yml up -d
      - run:
           name: Wait for run-time generated files
           command: |
             docker-compose -f ./tw-base/docker-compose.yml exec \
             server /bin/sh -c "./wait-for-file src/generated/prisma.ts"
      - run:
           name: Deploy
           command: |
            IMAGE_ID=$(docker-compose -f ./tw-base/docker-compose.yml images -q server)
            docker login --username=_ --password=$HEROKU_TOKEN registry.heroku.com

             if [[ $CIRCLE_BRANCH == "develop" ]]; then
               docker tag $IMAGE_ID registry.heroku.com/tw-server-52/web
               docker push registry.heroku.com/tw-server-52/web
             fi

             if [[ $CIRCLE_BRANCH == "master" ]]; then
               docker tag $IMAGE_ID registry.heroku.com/tw-server-prod/web
               docker push registry.heroku.com/tw-server-prod/web
             fi
